#!/bin/bash
i=0
for neturl in `cat ./conf/sites`
do 
	let i=${i}+1
	rm site_tmp$i >> rubish
	rm site_url$i >> rubish
	echo $neturl
#	curl $neturl >> rubish
	curl $neturl >> site_tmp$i
	pattern="${neturl}post/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/[0-9]\{11\}"
#	echo $pattern
	grep -o "$pattern" site_tmp$i | sort -r | uniq >> site_url$i
done
i=0
for line in `cat site_url1`
do
	url1_array[$i]=$line
	let i=${i}+1
done
echo ${url1_array[@]}
i=0
for line in `cat site_url2`
do
        url2_array[$i]=$line
        let i=${i}+1
done
echo ${url2_array[@]}
i=0
for line in `cat site_url3`
do
        url3_array[$i]=$line
        let i=${i}+1
done
echo ${url3_array[@]} 
for i in {0..9}
do
	echo $i
	if ! grep "${url1_array[$i]}" ./diandian/lasturl
	then
		rm nowurl >> rubish 
		echo ${url1_array[$i]} >> nowurl
		break
	fi
	echo "passed url1_array[$i]"
	if ! grep "${url2_array[$i]}" ./diandian/lasturl
        then 
                rm nowurl >> rubish
                echo ${url2_array[$i]} >> nowurl
                break
        fi
	echo "passed url2_array[$i]"
	if ! grep "{$url3_array[${i}]}" ./diandian/lasturl
        then 
                rm nowurl >> rubish
                echo ${url3_array[$i]} >> nowurl
                break
        fi
	echo "passed url3_array[$i]"
done

cat nowurl >> ./diandian/url_temp
cat ./diandian/lasturl	>> ./diandian/url_temp
rm ./diandian/lasturl
mv ./diandian/url_temp ./diandian/lasturl

rm site_tmp1 site_tmp2 site_tmp3
rm site_url1 site_url2 site_url3
rm rubish
