#!/bin/bash

#prepare mail subject
subject='The '`date +%W`'th '`date +%A`' for you'
echo $subject

#prepare mail content
rm temp
cat template/head >> temp
#echo '今日一语:' >> temp
cat diandian/content >> temp
cat template/end >> temp
cat temp

#send mail to address in maillist
for mailaddress in `cat ./conf/maillist`
do
	cat temp | mail -s "$subject" $mailaddress
done
echo "----------------------" >> ./logs/sendmail
date >> ./logs/sendmail
cat temp >> ./logs/sendmail
rm temp
